# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: about/
    weight: 100

  - name: Development
    url: backend
    weight: 200
  - parent: Development
    name: back-end
    url: backend
    weight: 210
  - parent: Development
    name: DB
    url: db
    weight: 220

  - name: Interest
    url: football
    weight: 300
  - parent: Interest
    name: football
    url: football
    weight: 310
  - parent: Interest
    name: baseball
    url: baseball
    weight: 320

  - name: Music
    url: rock
    weight: 400
  - parent: Music
    name: Rock
    url: rock
    weight: 410
  - parent: Music
    name: Hip Hop
    url: hiphop
    weight: 420

  - name: Project
    url: project1
    weight: 500
  - parent: Project
    name: project1
    url: project1
    weight: 510
  - parent: Project
    name: project2
    url: project2
    weight: 520
  - parent: Project
    name: project3
    url: project3
    weight: 530

  - name: Contact
    url: contact
    weight: 600

