# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: about/
    weight: 100

  - name: Skill
    url: skill
    weight: 200


  - name: Project
    url: gameproject
    weight: 300
  - parent: Project
    name: game project
    url: gameproject
    weight: 310
  - parent: Project
    name: map project
    url: mapproject
    weight: 320
  - parent: Project
    name: mall project
    url: mallproject
    weight: 330


  - name: Interest
    url: football
    weight: 300
  - parent: Interest
    name: football
    url: football
    weight: 310
  - parent: Interest
    name: baseball
    url: baseball
    weight: 320

  - name: Music
    url: rock
    weight: 400
  - parent: Music
    name: Rock
    url: rock
    weight: 410
  - parent: Music
    name: Hip Hop
    url: hiphop
    weight: 420


  - name: Contact
    url: contact
    weight: 500

